spring.datasource.url=${APPOINTMENT_DB_URL:jdbc:postgresql://localhost:5432/appointmentdb}
spring.datasource.username=${APPOINTMENT_DB_USERNAME:appointmentdb}
spring.datasource.password=${APPOINTMENT_DB_PASSWORD:appointmentdb}

security.jwt.enforce=false
